name: Try Clone
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy Express app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            mkdir ~/repo 
            cd ~/repo 
            git clone git@github.com:mastree/wedding-site-be.git
            echo 'Deployment successful to digital ocean' 
